default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= "#{ENV['DATABASE_NAME']}_dev" %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASS'] %>

test:
  <<: *default
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= "#{ENV['DATABASE_NAME']}_test" %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASS'] %>

production:
  <<: *default
  host: <%= Rails.application.credentials.database[:host] %>
  database: <%= Rails.application.credentials.database[:name] %>
  username: <%= Rails.application.credentials.database[:user] %>
  password: <%= Rails.application.credentials.database[:pass] %>
