default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  host: localhost
  database: devcoin_dev
  username: vbruk

test:
  <<: *default
  host: localhost
  database: devcoin_test
  username: vbruk

production:
  <<: *default
  host: <%= Rails.application.credentials.database[:host] %>
  database: <%= Rails.application.credentials.database[:name] %>
  username: <%= Rails.application.credentials.database[:user] %>
  password: <%= Rails.application.credentials.database[:pass] %>
